[package]
name = "AccountExample"
version = "0.0.0"

[addresses]
Std = "0x1"
Async = "0x1"
This = "0x3"

[build]
language_flavor = "async"

[dependencies]
MoveAsyncLib = { local = "../../move-async-lib" }
MoveStdlib = { local = "../../../move-stdlib" }
