[package]
name = "MoveTableExtension"
version = "1.0.0"

[addresses]
std = "_"
Extensions = "_"

[dev-addresses]
std = "0x1"
Extensions = "0x2"

[dependencies]
MoveStdlib = { local = "../../move-stdlib" }
MoveNursery = { local = "../../move-stdlib/nursery" }
